#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# ── Setup ─────────────────────────────────────────────────────────────────
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"
# shellcheck disable=SC1091
source ~/miniforge3/etc/profile.d/conda.sh && conda activate nckh
H=../.claude/skills/kaggle-training-notebook/scripts
ROT=scripts/rotate_kaggle_creds.py
ACCOUNTS=(minhtran0601 odixe0502 catbaochau trietbackup minhtriethihi khanhmay0304 minhtrit06 odixeuit)
ORIG_ACTIVE=$(python -c 'import json;print(json.load(open("'"$HOME"'/.kaggle/credentials.json"))["username"])' 2>/dev/null || true)
DONE_KGAT=(); DONE_OAUTH=()

banner "Kaggle credential rotation — 8 accounts"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight"
say "Active CLI login now: ${ORIG_ACTIVE:-none}. It is restored in the last stage."
say "Every saved refresh token is checked first — a dead one needs a browser login anyway."
python "$H/kaggle_account.py" health || warn "some snapshot is unhealthy; its OAuth stage will still create a fresh one"
say ""
say "For each account you will, in the browser, logged in as THAT account:"
step "1. create a new API token (Settings → API) and paste it here (hidden input)"
step "2. run 'kaggle auth login --force' — the browser opens, approve, come back"
say "Old values are revoked through the API right after the new ones verify. Either half"
say "of an account can be skipped; the wizard never revokes anything it has not replaced."
warn "Do NOT paste tokens into a chat window: they end up in transcripts on disk."
pause

# ── Stages 2–9: one per account ───────────────────────────────────────────
rotate_account() {
  local U="$1"
  stage "$U"
  say "Log OUT of kaggle.com in the browser, then log IN as ${BOLD}$U${RESET} before continuing."
  open_url "https://www.kaggle.com/settings"
  pause "Logged in as $U? Press Enter."

  # ── half A: KGAT API token (MCP bearer + CLI/SDK token)
  if confirm "Rotate the KGAT API token of $U?"; then
    step "Settings → API → create a new token; copy the KGAT_… value."
    step "If the page lists the old token, delete it there too (the wizard also tries via the API)."
    ask_secret NEW_KGAT "Paste the new KGAT token for $U:"
    if printf '%s' "$NEW_KGAT" | python "$ROT" install-kgat "$U"; then
      DONE_KGAT+=("$U")
    else
      SKIPPED+=("$U: KGAT not rotated (verification failed)")
    fi
    NEW_KGAT=""
  else
    SKIPPED+=("$U: KGAT kept")
  fi

  # ── half B: OAuth refresh token (CLI login)
  if confirm "Rotate the OAuth refresh token of $U (browser login)?"; then
    local act
    act=$(python -c 'import json;print(json.load(open("'"$HOME"'/.kaggle/credentials.json"))["username"])' 2>/dev/null || true)
    if [[ -n "$act" && "$act" != "$U" ]]; then
      python "$H/kaggle_account.py" save "$act" >/dev/null && note "snapshot of the current login ($act) refreshed first"
    fi
    step "A browser tab opens: approve the CLI as $U. (No browser? Ctrl-C and use --no-launch-browser by hand.)"
    if kaggle auth login --force && python "$ROT" rotate-oauth "$U"; then
      DONE_OAUTH+=("$U")
    else
      warn "login or snapshot step failed for $U; the previous snapshot is untouched"
      SKIPPED+=("$U: OAuth not rotated")
    fi
  else
    SKIPPED+=("$U: OAuth kept")
  fi
  pause "Done with $U. Press Enter for the next account."
}

for U in "${ACCOUNTS[@]}"; do rotate_account "$U"; done

# ── Stage 10: restore the active account and re-point every host config ──
stage "Restore & resync"
if [[ -n "$ORIG_ACTIVE" ]]; then
  say "Switching the CLI back to $ORIG_ACTIVE (this also rewrites .mcp.json here)."
  python "$H/kaggle_account.py" use "$ORIG_ACTIVE" --confirm || warn "switch back failed — run: kaggle_account.py use $ORIG_ACTIVE --confirm"
fi
say "Replacing every rotated bearer in .mcp.json / .vscode/mcp.json under ~/nckh:"
python "$ROT" resync-hosts ~/nckh
say ""
python "$H/kaggle_account.py" health || true
note "rotated KGAT: ${DONE_KGAT[*]:-none}"
note "rotated OAuth: ${DONE_OAUTH[*]:-none}"
warn "Reconnect the MCP client of the host you use (Claude Code: /mcp) — a live client keeps its old bearer."
warn "Old token values still sit in ~/.claude/projects/*.jsonl and ~/.vscode-server/data/logs; they are dead now,"
warn "but ask the agent to scrub or delete those files if you want them gone from disk."
# ──────────────────────────────────────────────────────────────────────────

finish
